name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Chrome
        run: |
          apt install google-chrome-stable
      - name: Install seleniumbase
        run: pip install seleniumbase
      - name: Install chromedriver
        run: |
         seleniumbase install chromedriver
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f testproject/requirements.txt ]; then pip install -r testproject/requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest --alluredir=allure-results
